# Add account credentials and API keys here.
# See http://railsapps.github.io/rails-environment-variables.html
# This file should be listed in .gitignore to keep your settings secret!
# Each entry sets a local environment variable.
# For example, setting:
# GMAIL_USERNAME: Your_Gmail_Username
# makes 'Your_Gmail_Username' available as ENV["GMAIL_USERNAME"]

# Add application configuration variables here, as shown below.
#
PROJECT_ROOT: /Users/photoboothmacmini/Desktop
EVENTS_PATH: /Users/photoboothmacmini/Desktop/PhotoboothPopUp Sessions
PRINT_PATH: /Users/photoboothmacmini/Desktop/PhotoboothPopUp Print

PRINT_TO_FOLDER: "YES"

GIF_MODE: "NO"
MAX_PHOTOS_IN_SET: 6
GIF_DELAY: 30

IMAGE_RATIO: "4:6"

MOVE_FROM_CAPTURE_FOLDER: "NO"

SHARE_COPY_EMAIL_SUBJECT: ""
SHARE_COPY_EMAIL_BODY: ""
SHARE_COPY_SOCIAL: ""
SHARE_COPY_TWITTER: ""


# Display photos
# Use 326 for landscape photos, 242 for portrait 
IMAGE_WIDTH: 242
#IMAGE_HEIGHT: 490

BRANDED_IMAGE_WIDTH: 1200 #1000
BRANDED_IMAGE_HEIGHT: 1800 #1500

BRANDED_IMAGE_WIDTH_GIF: 600 #1000
BRANDED_IMAGE_HEIGHT_GIF: 900 #1500

DISPLAY_IMAGE_WIDTH: 350
DISPLAY_IMAGE_HEIGHT: 525

PRINT_IMAGE_WIDTH: 1200
PRINT_IMAGE_HEIGHT: 1800

GIF_PRINT_MARGIN_TOP: 0
GIF_PRINT_MARGIN_RIGHT: 0
GIF_PRINT_MARGIN_BOTTOM: 0
GIF_PRINT_MARGIN_LEFT: 0

# Mailer
#GMAIL_USERNAME: "pboothup@gmail.com"
#GMAIL_PASSWORD: "popupphotos"

# Twilio
#TWILIO_SID: 'AC3ad723e6886607c1b8eea89116856da4'
#TWILIO_TOKEN: '7b7613371ce0333989bbf6df80a63577'
#TWILIO_NUMBER: '646-461-7671'

# Sharing options
#

#GOOGLE_CLIENT_ID: '301526465844-qk7vafmerabugapepov8395n72pdnsms.apps.googleusercontent.com'
#GOOGLE_CLIENT_SECRET: 'zKZSnkmx-2YWoT4PIr3t0FMc'

#PICASA_ID: "pboothup@gmail.com"
#PICASA_PASSWORD: "popupphotos"

TWITTER_KEY: "w0GY9v8iCCB2I27n7Wrhg"
TWITTER_SECRET: "Cv2v7vjWy8pAg7aST8tpsR4WhJUf3BHPL35GR4XtNo"

FACEBOOK_KEY: "613102788765274"
FACEBOOK_SECRET: "f37a71a54e7a1e4f90feac13376505b4"

#AMAZON_S3_KEY: "AKIAJDG32MVVNPRBLWHA"
#AMAZON_S3_SECRET: "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"

BITLY_USERNAME: "pboothup"
BITLY_TOKEN: "eb3ccacb67ab983925bbed37530aaf738fd8f4a0"

# Test account
#SMUGMUG_KEY: "atHIe9KA1pJMc3pE32Lkse5VYkCKqHZo"
#SMUGMUG_SECRET: "886144bd58dfb7f90fc5668a56d3fb7e"
#SMUGMUG_ACCESS_TOKEN: "9c72d3b807b63ffb9c341613542f217a"
#SMUGMUG_ACCESS_SECRET: "6c49eb2456d682b5c7392e6e14eb95e5aafeb57769bdf878e821159a285b807c"
#SMUGMUG_ALBUM_TITLE: "Test"

# NBC Universal
#SMUGMUG_KEY: "JDlsnqeuFbS6wPLz0DlzWbJYqMqdhQZB"
#SMUGMUG_SECRET: "6adf415dff11fcb8cfbfbdecf7eba3a1"
#SMUGMUG_ACCESS_TOKEN: "4d771e270ec34e0438b2de02f6e8238e"
#SMUGMUG_ACCESS_SECRET: "e78f618b08822aad684c0b3714cbe37be2733ad5979aa6a739d857c44a5cff72"
#SMUGMUG_ALBUM_TITLE: "YOUR ANIMATED GIFS"

# SATISFACTION USA
#SMUGMUG_KEY: "EcmzaOSwcY8jlBYErAdUOdijV62mpa0k"
#SMUGMUG_SECRET: "15db35cb5deeace0635a8ca6db7c6f29"
#SMUGMUG_ACCESS_TOKEN: "3b8d3e7eee87a23bb39a842ff71faf33"
#SMUGMUG_ACCESS_SECRET: "df65de67e77e912ee5e4df9cb46fa6a39698b0ba5d55819722da4040ce5b7d31"
#SMUGMUG_ALBUM_TITLE: "None"